<a href="https://colab.research.google.com/github/Adi13102005/Simple_Python_Program/blob/main/Practical3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a) Create a 3x3 square matrix and compute its determinant

In [ ]:
import numpy as np

# a) Create a 3x3 square matrix
matrix_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original 3x3 matrix:")
display(matrix_a)

# Compute its determinant
determinant_a = np.linalg.det(matrix_a)
print(f"\nDeterminant of the matrix: {determinant_a}")

b) Find the inverse of the matrix

In [6]:
import numpy as np

A = np.array([[1,2,3],
              [0,1,4],
              [5,6,0]])

print(np.linalg.inv(A))


[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


c) Solve the system of linear equations using NumPy:
 2x + 3y = 10
 4x + 5y = 20

In [7]:


# Represent the coefficients matrix (A)
coefficients = np.array([
    [2, 3],
    [4, 5]
])

# Represent the constants vector (b)
constants = np.array([10, 20])

print("\nCoefficients matrix (A):")
display(coefficients)
print("\nConstants vector (b):")
display(constants)

# Solve the system Ax = b for x
solution = np.linalg.solve(coefficients, constants)

print(f"\nSolution for x and y: x = {solution[0]:.2f}, y = {solution[1]:.2f}")

# Verify the solution
verification_eq1 = 2 * solution[0] + 3 * solution[1]
verification_eq2 = 4 * solution[0] + 5 * solution[1]
print(f"Verification: 2x + 3y = {verification_eq1:.2f} (expected 10)")
print(f"Verification: 4x + 5y = {verification_eq2:.2f} (expected 20)")


Coefficients matrix (A):


array([[2, 3],
       [4, 5]])


Constants vector (b):


array([10, 20])


Solution for x and y: x = 5.00, y = 0.00
Verification: 2x + 3y = 10.00 (expected 10)
Verification: 4x + 5y = 20.00 (expected 20)
